application:
  name: wthhyb-sacha-house
  port: 80
  healthPath: /

environments:
  staging:
    domain: staging.wthhyb.sacha.house
    noIndex: true
  production:
    domain: wthhyb.sacha.house

resources:
  cpu: 200
  memory: 128
