name: "wthhyb.sacha.house"
description: "What the hell have you built. - https://wthhyb.sacha.house\r\nsee https://x.com/codinghorror/status/347070841059692545"
topics:
  - "react"
homepage: ""
source:
  provider: gitlab
  namespace: "sachahjkl"
  path: "sachahjkl/wthhyb.sacha.house"
