name: Deploy production

on:
  workflow_dispatch:

jobs:
  production:
    permissions:
      attestations: read
      contents: read
      id-token: write
      packages: read
    uses: sachahjkl/deployment-actions/.github/workflows/application-production.yml@v3.0.1
