name: Deploy production

on:
  workflow_dispatch:

jobs:
  production:
    permissions:
      attestations: read
      contents: read
      id-token: write
      packages: read
    uses: sachahjkl/deployment-actions/.github/workflows/application-production.yml@2c48656195637544e57df59033ae62859f379649
    with:
      local-pack: true
